export const essay_types: { [level: string]: string[] | null } = {
  "Primary Level": [
    "Narrative",
    "Descriptive",
    "Persuasive",
    "Expository",
    "Opinion",
    "Imaginative",
    "Personal Reflection",
    "My Favourite...",
  ],
  "Secondary Level": [
    "Narrative",
    "Descriptive",
    "Persuasive",
    "Expository",
    "Opinion",
    "Analytical",
    "Comparative",
    "Reflective",
    "Argumentative",
  ],
  "Undergraduate Level": [
    "Research",
    "Argumentative",
    "Comparative",
    "Critical Review",
    "Reflective",
    "Expository",
    "Persuasive",
    "Scientific",
  ],
  "Academic Writing Task 1": ["Report on A Chart"],
  "Academic Writing Task 2": [
    "Opinion",
    "Discussion",
    "Advantage/Disadvantage",
    "Direction Question",
    "Solution",
  ],
  "General Training Writing Task 1": ["Letter"],
  "General Training Writing Task 2": [
    "Opinion",
    "Discussion",
    "Advantage / Disadvantage",
    "Direction Question",
    "Solution",
  ],
  "Integrated Writing Task": null,
  "Independent Writing Task": [
    "Agree / Disagree",
    "Multiple Choice",
    "Preference",
    "Imaginary Situation",
  ],
  "Academic Discussion Task": null,
  "Analytical Writing - Issue Task": null,
  "Analytical Writing - Argument Task": null,
};
