import { Container, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "./Footer";
import NavBar from "./NavBar";
import QueryClientProvider from "./QueryClientProvider";
import "./globals.css";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider>
          <Providers>
            <Theme accentColor="sky">
              <NavBar />
              <Container m="6">
                <main>{children}</main>
              </Container>
              <Footer />
            </Theme>
          </Providers>
        </QueryClientProvider>
      </body>
    </html>
  );
}
